creatures:
  cow:
    head_drop_probability: 100
    token:
      name: "Cow Token"
      heads: 400
      xp: 25
      player_kills: 1
    masks:
      tier_1:
        name: "Cow Mask"
        lore: "Tier 1"
        tokens: 1
        money: 100 m0
      tier_2:
        name: "Cow Mask"
        lore: "Tier 2"
        tokens: 2
        money: 2000
      tier_3:
        name: "Cow Mask"
        lore: "Tier 3"
        tokens: 3
        money: 3000
  pig:
    head_drop_probability: 100
    token:
      name: "Pig Token"
      heads: 400
      xp: 25
      player_kills: 1
    masks:
      tier_1:
        name: "Pig Mask"
        lore: "Tier 1"
        tokens: 1
        money: 1000
      tier_2:
        name: "Pig Mask"
        lore: "Tier 2"
        tokens: 2
        money: 2000
      tier_3:
        name: "Pig Mask"
        lore: "Tier 3"
        tokens: 3
        money: 3000
  iron_golem:
    head_drop_probability: 100
    token:
      name: "Iron Golem Token"
      heads: 400
      xp: 25
      player_kills: 1
    masks:
      tier_1:
        name: "Iron Golem Mask"
        lore: "Tier 1"
        tokens: 1
        money: 1000
      tier_2:
        name: "Iron Golem Mask"
        lore: "Tier 2"
        tokens: 2
        money: 2000
      tier_3:
        name: "Iron Golem Mask"
        lore: "Tier 3"
        tokens: 3
        money: 3000
  skeleton:
    head_drop_probability: 100
    token:
      name: "Skeleton Token"
      heads: 400
      xp: 25
      player_kills: 1
    masks:
      tier_1:
        name: "Skeleton Mask"
        lore: "Tier 1"
        tokens: 1
        money: 1000
      tier_2:
        name: "Skeleton Mask"
        lore: "Tier 2"
        tokens: 2
        money: 2000
      tier_3:
        name: "Skeleton Mask"
        lore: "Tier 3"
        tokens: 3
        money: 3000
  zombie:
    head_drop_probability: 100
    token:
      name: "Zombie Token"
      heads: 400
      xp: 25
      player_kills: 1
    masks:
      tier_1:
        name: "Zombie Mask"
        lore: "Tier 1"
        tokens: 1
        money: 1000
      tier_2:
        name: "Zombie Mask"
        lore: "Tier 2"
        tokens: 2
        money: 2000
      tier_3:
        name: "Zombie Mask"
        lore: "Tier 3"
        tokens: 3
        money: 3000
  blaze:
    head_drop_probability: 100
    token:
      name: "Blaze Token"
      heads: 400
      xp: 25
      player_kills: 1
    masks:
      tier_1:
        name: "Blaze Mask"
        lore: "Tier 1"
        tokens: 1
        money: 1000
      tier_2:
        name: "Blaze Mask"
        lore: "Tier 2"
        tokens: 2
        money: 2000
      tier_3:
        name: "Blaze Mask"
        lore: "Tier 3"
        tokens: 3
        money: 3000
permissions:
  mob_head_drops: "headhunting.mob_head_drops"
  redeem: "headhunting.redeem"
messages:
  no_permissions_message: "No permissions"
  no_console_command_message: "Console can not execute this command"
options:
  token_inventory_name: "Tokens"
database:
  host: "localhost"
  port: 3306
  database: ""
  username: ""
  password: ""
  table: ""
