creatures:
  cow:
    name: "Cow"
    head:
      type: "MHF_Cow"
      name: "Cow's Head"
    head_drop_probability: 100
    token:
      name: "Cow Token"
      heads:
        text: "Heads Required: "
        required: 400
      xp:
        text: "XP Required: "
        required: 25
      player_kills:
        text: "Kills Required: "
        required: 1
    masks:
      name: "Cow Mask"
      tier_1:
        name: "Tier 1"
        tokens: 1
        money: 100
      tier_2:
        name: "Tier 2"
        tokens: 2
        money: 2000
      tier_3:
        name: "Tier 3"
        tokens: 3
        money: 3000
  pig:
    name: "Pig"
    head:
      type: "MHF_Pig"
      name: "Pig's Head"
    head_drop_probability: 100
    token:
      name: "Pig Token"
      heads:
        text: "Heads Required: "
        required: 400
      xp:
        text: "XP Required: "
        required: 25
      player_kills:
        text: "Kills Required: "
        required: 1
    masks:
      name: "Pig Mask"
      tier_1:
        name: "Tier 1"
        tokens: 1
        money: 1000
      tier_2:
        name: "Tier 2"
        tokens: 2
        money: 2000
      tier_3:
        name: "Tier 3"
        tokens: 3
        money: 3000
  iron_golem:
    name: "Iron Golem"
    head:
      type: "MHF_Golem"
      name: "Iron Golem's Head"
    head_drop_probability: 100
    token:
      name: "Iron Golem Token"
      heads:
        text: "Heads Required: "
        required: 400
      xp:
        text: "XP Required: "
        required: 25
      player_kills:
        text: "Kills Required: "
        required: 1
    masks:
      name: "Iron Golem Mask"
      tier_1:
        name: "Tier 1"
        tokens: 1
        money: 1000
      tier_2:
        name: "Tier 2"
        tokens: 2
        money: 2000
      tier_3:
        name: "Tier 3"
        tokens: 3
        money: 3000
  skeleton:
    name: "Skeleton"
    head:
      type: "MHF_Skeleton"
      name: "Skeleton's Head"
    head_drop_probability: 100
    token:
      name: "Skeleton Token"
      heads:
        text: "Heads Required: "
        required: 400
      xp:
        text: "XP Required: "
        required: 25
      player_kills:
        text: "Kills Required: "
        required: 1
    masks:
      name: "Skeleton Mask"
      tier_1:
        name: "Tier 1"
        tokens: 1
        money: 1000
      tier_2:
        name: "Tier 2"
        tokens: 2
        money: 2000
      tier_3:
        name: "Tier 3"
        tokens: 3
        money: 3000
  zombie:
    name: "Zombie"
    head:
      type: "MHF_Zombie"
      name: "Zombie's Head"
    head_drop_probability: 100
    token:
      name: "Zombie Token"
      heads:
        text: "Heads Required: "
        required: 400
      xp:
        text: "XP Required: "
        required: 25
      player_kills:
        text: "Kills Required: "
        required: 1
    masks:
      name: "Zombie Mask"
      tier_1:
        name: "Tier 1"
        tokens: 1
        money: 1000
      tier_2:
        name: "Tier 2"
        tokens: 2
        money: 2000
      tier_3:
        name: "Tier 3"
        tokens: 3
        money: 3000
  blaze:
    name: "Blaze"
    head:
      type: "MHF_Blaze"
      name: "Blaze's Head"
    head_drop_probability: 100
    token:
      name: "Blaze Token"
      heads:
        text: "Heads Required: "
        required: 400
      xp:
        text: "XP Required: "
        required: 25
      player_kills:
        text: "Kills Required: "
        required: 1
    masks:
      name: "Blaze Mask"
      tier_1:
        name: "Tier 1"
        tokens: 1
        money: 1000
      tier_2:
        name: "Tier 2"
        tokens: 2
        money: 2000
      tier_3:
        name: "Tier 3"
        tokens: 3
        money: 3000
permissions:
  mob_head_drops: "headhunting.mob_head_drops"
  redeem: "headhunting.redeem"
messages:
  no_permissions_message: "No permissions"
  no_console_command_message: "Console can not execute this command"
options:
  token_inventory_name: "Tokens"
database:
  host: "localhost"
  port: 3306
  database: ""
  username: ""
  password: ""
  table: ""
