name: HeadHunting
author: "Steven Rafferty"
version: 0.0.6
description: A plugin that enables you to collect mob heads to obtain masks
main: net.stevenrafferty.headhunting.Main

commands:
  redeem:
    description: Exchanges mob heads for tokens
    usage: /redeem
  souls:
    description: Tells you how many souls you have collected
    usage: /souls