name: HeadHunting
author: "Steven Rafferty"
version: 0.0.13
description: A plugin that enables you to collect mob heads to obtain masks
main: net.stevenrafferty.headhunting.Main
api-version: 1.16

commands:
  redeem:
    description: Exchanges mob heads for tokens
    usage: /redeem
  souls:
    description: Tells you how many souls you have collected
    usage: /souls
  masks:
    description: Exchange tokens and money for Masks
    usage: /masks
  upgrade:
    description: Upgrades mask to the next tier
    usage: /upgrade
  headhunting:
    description: Lists all of the avaliable commands
    usage: /headhunting
    aliases: [hh]